

SAMPLE_FSPATH = example01

print:
	@echo nats ex

flu-create:
	flutter create $(SAMPLE_FSPATH)

flu-desk-local-init: ## flu-desk-local-init
	cd $(SAMPLE_FSPATH) && hover init

flu-desk-local-run: ## flu-desk-local-run
	cd $(SAMPLE_FSPATH) && hover run

flu-web-run:
	cd $(SAMPLE_FSPATH) && flutter run -d chrome